/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromotionRouteImport } from './routes/promotion'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const PromotionRoute = PromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/promotion': typeof PromotionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/promotion': typeof PromotionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/promotion': typeof PromotionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/menu' | '/promotion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/menu' | '/promotion'
  id: '__root__' | '/' | '/contact' | '/menu' | '/promotion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MenuRoute: typeof MenuRoute
  PromotionRoute: typeof PromotionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promotion': {
      id: '/promotion'
      path: '/promotion'
      fullPath: '/promotion'
      preLoaderRoute: typeof PromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/contact' {
  const createFileRoute: CreateFileRoute<
    '/contact',
    FileRoutesByPath['/contact']['parentRoute'],
    FileRoutesByPath['/contact']['id'],
    FileRoutesByPath['/contact']['path'],
    FileRoutesByPath['/contact']['fullPath']
  >
}
declare module './routes/menu' {
  const createFileRoute: CreateFileRoute<
    '/menu',
    FileRoutesByPath['/menu']['parentRoute'],
    FileRoutesByPath['/menu']['id'],
    FileRoutesByPath['/menu']['path'],
    FileRoutesByPath['/menu']['fullPath']
  >
}
declare module './routes/promotion' {
  const createFileRoute: CreateFileRoute<
    '/promotion',
    FileRoutesByPath['/promotion']['parentRoute'],
    FileRoutesByPath['/promotion']['id'],
    FileRoutesByPath['/promotion']['path'],
    FileRoutesByPath['/promotion']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MenuRoute: MenuRoute,
  PromotionRoute: PromotionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
